### ISSUE TITLE
License on these BeOS projects

### ISSUE THREAD

**Issue by scottmc** [jwiggins/BeOS-Projects#1]
@jwiggins I'm assuming you also wrote this one: https://github.com/haikuports/haikuports/issues/3055
What license is your code under?  Would you be ok with putting it under MIT or some other open source license?  We have moved many old BeOS programs over to HaikuArchives (https://github.com/HaikuArchives) and have updated a many of them to work under Haiku.

**Comment by jwiggins** [comment]
Yes, that's me. I'm fine with MIT... I'll add a license to this repo.

**Comment by jwiggins** [comment]
Done.
